# -----------------------------------------------------
# General window layout and colors
# name: "Default"
# -----------------------------------------------------

general {
    gaps_in = 5 
    gaps_out = 5
    border_size = 1
    col.active_border = rgb(120,120,135)
    col.inactive_border = rgb(65,65,85)
    
    layout = dwindle
    resize_on_border = true
}
