color0 #262b2c
color1 #fd4663
color2 #9aadb2
color3 #8d9aa5
color4 #8f95a3
color5 #b7c4c8
color6 #b8c0c7
color7 #f2f2f3
color8 #646b6c
color9 #fd4663
color10 #9aadb2
color11 #8d9aa5
color12 #8f95a3
color13 #b7c4c8
color14 #b8c0c7
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1c2021
background            #1c2021
foreground            #f2f2f3
selection_foreground  #b0b4b5
selection_background  #262b2c
active_border_color   #9aadb2
inactive_border_color #262b2c
url_color             #9aadb2

active_tab_foreground   #1c2022
active_tab_background   #9aadb2
inactive_tab_foreground #b0b4b5
inactive_tab_background #262b2c
cursor_trail_color      #b0b4b5
