color0 #26262c
color1 #fd4663
color2 #989ab3
color3 #918da5
color4 #988fa3
color5 #b6b7c9
color6 #bab8c7
color7 #f2f2f3
color8 #67676e
color9 #fd4663
color10 #989ab3
color11 #918da5
color12 #988fa3
color13 #b6b7c9
color14 #bab8c7
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1c1d21
background            #1c1d21
foreground            #f2f2f3
selection_foreground  #b0b1b5
selection_background  #26262c
active_border_color   #989ab3
inactive_border_color #26262c
url_color             #989ab3

active_tab_foreground   #1c1c22
active_tab_background   #989ab3
inactive_tab_foreground #b0b1b5
inactive_tab_background #26262c
cursor_trail_color      #b0b1b5
