color0 #29262c
color1 #fd4663
color2 #a69dae
color3 #9e8fa3
color4 #a38fa3
color5 #c0b9c5
color6 #c2b9c5
color7 #f2f2f3
color8 #6a666d
color9 #fd4663
color10 #a69dae
color11 #9e8fa3
color12 #a38fa3
color13 #c0b9c5
color14 #c2b9c5
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1e1c21
background            #1e1c21
foreground            #f2f2f3
selection_foreground  #b3b0b5
selection_background  #29262c
active_border_color   #a69dae
inactive_border_color #29262c
url_color             #a69dae

active_tab_foreground   #1f1c22
active_tab_background   #a69dae
inactive_tab_foreground #b3b0b5
inactive_tab_background #29262c
cursor_trail_color      #b3b0b5
