# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------
# Main monitor — ASUS PG27UCDM
# monitor=DP-1,3840x2160@240,0x0,1.666667,vrr,1
monitor=DP-1,3840x2160@240,0x0,1.666667,vrr,2


# Secondary monitor
monitor=DP-2,preferred,auto-right,1


vfr = true
